### ISSUE TITLE
GLV Battery Voltage Too Low Notification

### ISSUE THREAD

**Issue by atokosch** [smit-happens/YCP_EVOS#145] opened 2018-03-28 20:38 UTC
## End goal
Notify driver in more than one way than on the GLCD that the GLV batteries are running low. 

## Relevant Info/Links
Related to #95 #121

**Comment by atokosch** [comment] 2018-04-09 17:14
Look up table for 24 = 2.8v, etc.. 
Test with power supply and get readings

**Comment by atokosch** [comment] 2018-04-16 16:35
Unassigned others to show that I will implement this.

**Comment by smit-happens** [comment] 2018-04-22 21:56
duplicate of #95

**Closed by smit-happens** 2018-04-22 21:56 UTC
Labels: dash, duplicate, gui, help-wanted, question
